####################################################################################################
# Networks
####################################################################################################
networks:
  laravel:
    driver: bridge

services:
  ####################################################################################################
  # PHP
  ####################################################################################################
  php:
    build: .docker/php
    depends_on:
      - db
    ports:
      - 5173:5173
    volumes:
      - .:/var/www:cached
      - ./.docker/app/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
    entrypoint: ["/usr/local/bin/docker-entrypoint.sh"]
    networks:
      - laravel

  ####################################################################################################
  # Nginx
  ####################################################################################################
  nginx:
    image: nginx
    ports:
      - 8082:80
    volumes:
      - .:/var/www
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    networks:
      - laravel

  ####################################################################################################
  # DATABASE (MySQL)
  ####################################################################################################
  # db:
  #     image: mysql:8.1
  #     ports:
  #         - 3406:3306
  #     volumes:
  #         - .docker/db/data:/var/lib/mysql
  #         - .docker/logs:/var/log/mysql
  #         - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
  #         - .docker/db/sql:/docker-entrypoint-initdb.d
  #     environment:
  #         MYSQL_ROOT_PASSWORD: root
  #         MYSQL_DATABASE: sma
  #         MYSQL_USER: sma
  #         MYSQL_PASSWORD: sma
  #     networks:
  #       - laravel

  ####################################################################################################
  # phpMyAdmin
  ####################################################################################################
  # phpmyadmin:
  #     image: phpmyadmin/phpmyadmin
  #     ports:
  #         - 8080:80
  #     links:
  #         - db
  #     environment:
  #         PMA_HOST: db
  #         PMA_PORT: 3306
  #         PMA_ARBITRARY: 1
  #     volumes:
  #         - .docker/phpmyadmin/sessions:/sessions
  #     networks:
  #       - laravel

  ####################################################################################################
  # Adminer
  ####################################################################################################
  # adminer:
  #     image: adminer
  #     ports:
  #         - 9090:8080
  #     depends_on:
  #     - db
  #     networks:
  #       - laravel

  ####################################################################################################
  # Mailpit
  ####################################################################################################
  # mail:
  #     image: axllent/mailpit:latest
  #     ports:
  #     - 8025:8025
  #     - 1025:1025
  #     networks:
  #       - laravel

  ####################################################################################################
  # Redis
  ####################################################################################################
  # redis:
  #     image: redis:latest
  #     command: redis-server --appendonly yes
  #     volumes:
  #     - .docker/redis/data:/data
  #     ports:
  #     - 6379:6379
  #     networks:
  #       - laravel

  # ####################################################################################################
  # # DATABASE (MariaDB)
  # ####################################################################################################
  # db:
  #     image: mariadb:10.11
  #     ports:
  #         - 3306:3306
  #     volumes:
  #         - .docker/db/data:/var/lib/mysql
  #         - .docker/logs:/var/log/mysql
  #         - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
  #         - .docker/db/sql:/docker-entrypoint-initdb.d
  #     environment:
  #         MYSQL_ROOT_PASSWORD: root
  #         MYSQL_DATABASE: laravel_db_name
  #         MYSQL_USER: laravel_db_user
  #         MYSQL_PASSWORD: laravel_db_pass
  #     networks:
  #       - laravel

  ####################################################################################################
  # PostgreSQL
  ####################################################################################################
  db:
    image: postgres:16
    ports:
      - 5439:5432
    volumes:
      - .docker/db/data:/var/lib/postgresql/data
      - .docker/db/sql:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=sma
      - POSTGRES_PASSWORD=sma
      - POSTGRES_DB=sma
    networks:
      - laravel

  ####################################################################################################
  # pgAdmin
  ####################################################################################################
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=password
    depends_on:
      - db
    networks:
      - laravel
